"""
export-to-office.py
-------------------
BABOK V3 BA Assistant — Export Utility

Converts a filled markdown template section into a Microsoft Office file.
Supports: .docx (Word), .xlsx (Excel), .pptx (PowerPoint)

Usage:
    python export-to-office.py --input <md_file> --format docx|xlsx|pptx [OPTIONS]

Options:
    --input   Path to the filled markdown file (required)
    --format  Output format: docx, xlsx, or pptx (required)
    --section Section letter to extract, e.g. A, B, C (optional — exports all if omitted)
    --out     Output directory (default: outputs/)
    --title   Custom document title (optional)

Examples:
    python export-to-office.py --input references/templates/ka03/ba-planning-template.md --format docx --section C --out outputs/
    python export-to-office.py --input references/templates/ka03/ba-planning-template.md --format xlsx --section D
    python export-to-office.py --input references/templates/ka06/current-state-assessment-template-with-instructions.md --format pptx
"""

import argparse
import re
import sys
from pathlib import Path
from datetime import datetime


# ─── MARKDOWN PARSER ────────────────────────────────────────────────────────────

def parse_markdown(md_text: str) -> list[dict]:
    """
    Parse markdown into a list of blocks:
      {"type": "heading", "level": int, "text": str}
      {"type": "paragraph", "text": str}
      {"type": "table", "headers": list[str], "rows": list[list[str]]}
      {"type": "bullet", "text": str, "level": int}
    """
    blocks = []
    lines = md_text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]

        # Blank line
        if not line.strip():
            i += 1
            continue

        # Heading
        m = re.match(r'^(#{1,6})\s+(.*)', line)
        if m:
            blocks.append({"type": "heading", "level": len(m.group(1)), "text": m.group(2).strip()})
            i += 1
            continue

        # Table: detect separator row pattern (---) on next line
        if i + 1 < len(lines) and re.match(r'^\|[\s\-\|:]+\|$', lines[i + 1]):
            headers = [c.strip() for c in line.strip('|').split('|')]
            i += 2  # skip separator
            rows = []
            while i < len(lines) and lines[i].startswith('|'):
                rows.append([c.strip() for c in lines[i].strip('|').split('|')])
                i += 1
            blocks.append({"type": "table", "headers": headers, "rows": rows})
            continue

        # Bullet list
        m = re.match(r'^(\s*)[-*]\s+(.*)', line)
        if m:
            level = len(m.group(1)) // 2
            blocks.append({"type": "bullet", "text": m.group(2).strip(), "level": level})
            i += 1
            continue

        # Paragraph
        blocks.append({"type": "paragraph", "text": line.strip()})
        i += 1

    return blocks


def extract_section(blocks: list[dict], section_letter: str) -> list[dict]:
    """
    Extract blocks belonging to a section identified by heading text starting with
    'Section <letter>:' or '## <letter>.' pattern.
    Stops at the next same-level or higher heading.
    """
    letter = section_letter.upper()
    start = None
    start_level = None

    for idx, b in enumerate(blocks):
        if b["type"] == "heading":
            text = b["text"].upper()
            # Match: "SECTION A:", "A.", "A:", or heading that starts with the letter
            if re.match(rf'^(SECTION\s+)?{letter}[:\.]', text) or text.startswith(letter + ' '):
                start = idx
                start_level = b["level"]
                break

    if start is None:
        return blocks  # fallback: return everything

    result = []
    for b in blocks[start:]:
        if result and b["type"] == "heading" and b["level"] <= start_level:
            break
        result.append(b)

    return result if result else blocks


def clean_text(text: str) -> str:
    """Remove inline markdown markers like **bold**, *italic*, `code`."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    return text.strip()


# ─── DOCX EXPORT ────────────────────────────────────────────────────────────────

def export_docx(blocks: list[dict], output_path: Path, title: str):
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # ── Document style setup
    style_normal = doc.styles["Normal"]
    style_normal.font.name = "Calibri"
    style_normal.font.size = Pt(11)

    # Title
    t = doc.add_heading(title, level=0)
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Meta line
    meta = doc.add_paragraph(f"Generated by BABOK BA Assistant  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    meta.runs[0].font.size = Pt(9)

    doc.add_paragraph()  # spacer

    for b in blocks:
        if b["type"] == "heading":
            doc.add_heading(clean_text(b["text"]), level=min(b["level"], 4))

        elif b["type"] == "paragraph":
            text = clean_text(b["text"])
            if text:
                doc.add_paragraph(text)

        elif b["type"] == "bullet":
            text = clean_text(b["text"])
            style = "List Bullet 2" if b["level"] > 0 else "List Bullet"
            doc.add_paragraph(text, style=style)

        elif b["type"] == "table":
            headers = [clean_text(h) for h in b["headers"]]
            rows = [[clean_text(c) for c in row] for row in b["rows"]]
            if not headers:
                continue
            tbl = doc.add_table(rows=1 + len(rows), cols=len(headers))
            tbl.style = "Table Grid"

            # Header row
            for j, h in enumerate(headers):
                cell = tbl.rows[0].cells[j]
                cell.text = h
                cell.paragraphs[0].runs[0].bold = True
                cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                tc = cell._tc
                from docx.oxml.ns import qn
                from docx.oxml import OxmlElement
                tcPr = tc.get_or_add_tcPr()
                shd = OxmlElement("w:shd")
                shd.set(qn("w:fill"), "1F497D")
                shd.set(qn("w:color"), "auto")
                shd.set(qn("w:val"), "clear")
                tcPr.append(shd)

            # Data rows
            for i, row in enumerate(rows):
                for j, val in enumerate(row):
                    tbl.rows[i + 1].cells[j].text = val if val else ""

            doc.add_paragraph()  # space after table

    doc.save(output_path)
    return output_path


# ─── XLSX EXPORT ────────────────────────────────────────────────────────────────

def export_xlsx(blocks: list[dict], output_path: Path, title: str):
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = "BA Deliverable"

    HEADER_FILL = PatternFill("solid", fgColor="1F497D")
    HEADER_FONT = Font(bold=True, color="FFFFFF", name="Calibri", size=11)
    TITLE_FONT = Font(bold=True, name="Calibri", size=14)
    BODY_FONT = Font(name="Calibri", size=11)
    SECTION_FONT = Font(bold=True, name="Calibri", size=12, color="1F497D")
    THIN = Side(style="thin", color="BFBFBF")
    THIN_BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

    row = 1

    # Title row
    ws.cell(row=row, column=1, value=title).font = TITLE_FONT
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    ws.cell(row=row, column=1).alignment = Alignment(horizontal="center")
    row += 1

    # Meta
    ws.cell(row=row, column=1, value=f"BABOK BA Assistant  |  {datetime.now().strftime('%Y-%m-%d')}").font = Font(name="Calibri", size=9, color="808080")
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
    row += 2

    for b in blocks:
        if b["type"] == "heading":
            ws.row_dimensions[row].height = 18
            c = ws.cell(row=row, column=1, value=clean_text(b["text"]))
            if b["level"] <= 2:
                c.font = SECTION_FONT
            else:
                c.font = Font(bold=True, name="Calibri", size=11)
            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
            row += 1

        elif b["type"] == "paragraph":
            text = clean_text(b["text"])
            if text:
                c = ws.cell(row=row, column=1, value=text)
                c.font = BODY_FONT
                c.alignment = Alignment(wrap_text=True)
                ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
                row += 1

        elif b["type"] == "bullet":
            indent = "  " * b["level"]
            c = ws.cell(row=row, column=1, value=f"{indent}• {clean_text(b['text'])}")
            c.font = BODY_FONT
            ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=6)
            row += 1

        elif b["type"] == "table":
            headers = [clean_text(h) for h in b["headers"]]
            rows = [[clean_text(c) for c in r] for r in b["rows"]]
            col_count = len(headers)

            # Header row
            for j, h in enumerate(headers, start=1):
                c = ws.cell(row=row, column=j, value=h)
                c.font = HEADER_FONT
                c.fill = HEADER_FILL
                c.border = THIN_BORDER
                c.alignment = Alignment(horizontal="center", wrap_text=True)
                ws.column_dimensions[get_column_letter(j)].width = max(18, len(h) + 4)
            row += 1

            # Data rows
            for data_row in rows:
                for j, val in enumerate(data_row, start=1):
                    c = ws.cell(row=row, column=j, value=val or "")
                    c.font = BODY_FONT
                    c.border = THIN_BORDER
                    c.alignment = Alignment(wrap_text=True, vertical="top")
                row += 1

            row += 1  # spacer after table

    wb.save(output_path)
    return output_path


# ─── PPTX EXPORT ────────────────────────────────────────────────────────────────

def export_pptx(blocks: list[dict], output_path: Path, title: str):
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    NAVY = RGBColor(0x1F, 0x49, 0x7D)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    LIGHT_GRAY = RGBColor(0xF2, 0xF2, 0xF2)
    TEXT_DARK = RGBColor(0x26, 0x26, 0x26)

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]  # completely blank

    def add_slide():
        return prs.slides.add_slide(blank_layout)

    def add_textbox(slide, text, left, top, width, height,
                    font_size=18, bold=False, color=TEXT_DARK,
                    align=PP_ALIGN.LEFT, wrap=True, bg_color=None):
        from pptx.util import Emu
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = wrap
        p = tf.paragraphs[0]
        p.alignment = align
        run = p.add_run()
        run.text = clean_text(text)
        run.font.size = Pt(font_size)
        run.font.bold = bold
        run.font.color.rgb = color
        run.font.name = "Calibri"
        if bg_color:
            from pptx.oxml.ns import qn
            from lxml import etree
            sp = txBox._element
            spPr = sp.find(qn('p:spPr'))
            solidFill = etree.SubElement(spPr, qn('a:solidFill'))
            srgbClr = etree.SubElement(solidFill, qn('a:srgbClr'))
            srgbClr.set('val', f"{bg_color[0]:02X}{bg_color[1]:02X}{bg_color[2]:02X}")
        return txBox

    def add_table_slide(slide, headers, rows):
        """Add a table to a slide, auto-sizing columns."""
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        margin = Inches(0.5)
        top = Inches(1.5)
        width = prs.slide_width - 2 * margin
        height = Inches(0.4) * (len(rows) + 1)

        col_count = len(headers)
        row_count = len(rows) + 1  # include header

        tbl = slide.shapes.add_table(row_count, col_count, margin, top, width, height).table
        tbl.first_row = True

        for j, h in enumerate(headers):
            cell = tbl.cell(0, j)
            cell.text = clean_text(h)
            cell.fill.solid()
            cell.fill.fore_color.rgb = NAVY
            p = cell.text_frame.paragraphs[0]
            run = p.add_run() if not p.runs else p.runs[0]
            run.font.bold = True
            run.font.color.rgb = WHITE
            run.font.name = "Calibri"
            run.font.size = Pt(10)

        for i, row in enumerate(rows):
            for j, val in enumerate(row):
                cell = tbl.cell(i + 1, j)
                cell.text = clean_text(val) if val else ""
                if i % 2 == 0:
                    cell.fill.solid()
                    cell.fill.fore_color.rgb = LIGHT_GRAY
                p = cell.text_frame.paragraphs[0]
                run = p.add_run() if not p.runs else p.runs[0]
                run.font.name = "Calibri"
                run.font.size = Pt(10)

    # ── Title slide
    slide = add_slide()
    # Navy background bar
    from pptx.util import Inches
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        0, 0,
        prs.slide_width, Inches(2.5)
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = NAVY
    shape.line.fill.background()

    add_textbox(slide, title,
                Inches(0.8), Inches(0.6),
                prs.slide_width - Inches(1.6), Inches(1.5),
                font_size=32, bold=True, color=WHITE,
                align=PP_ALIGN.CENTER)
    add_textbox(slide, f"BABOK V3 | {datetime.now().strftime('%B %Y')}",
                Inches(0.8), Inches(2.0),
                prs.slide_width - Inches(1.6), Inches(0.5),
                font_size=14, color=RGBColor(0xCC, 0xD9, 0xEA),
                align=PP_ALIGN.CENTER)
    add_textbox(slide, "Generated by BABOK BA Assistant",
                Inches(0.8), Inches(6.8),
                prs.slide_width - Inches(1.6), Inches(0.4),
                font_size=9, color=RGBColor(0x80, 0x80, 0x80),
                align=PP_ALIGN.RIGHT)

    # ── Content slides
    current_slide = None
    y_cursor = Inches(1.5)
    MAX_Y = Inches(6.8)

    def new_content_slide(section_title=""):
        nonlocal current_slide, y_cursor
        current_slide = add_slide()
        # Top bar
        bar = current_slide.shapes.add_shape(1, 0, 0, prs.slide_width, Inches(0.8))
        bar.fill.solid()
        bar.fill.fore_color.rgb = NAVY
        bar.line.fill.background()
        if section_title:
            add_textbox(current_slide, section_title,
                        Inches(0.4), Inches(0.1),
                        prs.slide_width - Inches(0.8), Inches(0.6),
                        font_size=18, bold=True, color=WHITE)
        y_cursor = Inches(1.0)

    new_content_slide(title)

    for b in blocks:
        if b["type"] == "heading":
            if b["level"] <= 2:
                new_content_slide(clean_text(b["text"]))
            else:
                if y_cursor + Inches(0.5) > MAX_Y:
                    new_content_slide()
                add_textbox(current_slide, clean_text(b["text"]),
                            Inches(0.5), y_cursor,
                            prs.slide_width - Inches(1.0), Inches(0.45),
                            font_size=14, bold=True, color=NAVY)
                y_cursor += Inches(0.5)

        elif b["type"] == "paragraph":
            text = clean_text(b["text"])
            if not text:
                continue
            if y_cursor + Inches(0.45) > MAX_Y:
                new_content_slide()
            add_textbox(current_slide, text,
                        Inches(0.5), y_cursor,
                        prs.slide_width - Inches(1.0), Inches(0.45),
                        font_size=11)
            y_cursor += Inches(0.45)

        elif b["type"] == "bullet":
            prefix = "  " * b["level"] + "• "
            text = prefix + clean_text(b["text"])
            if y_cursor + Inches(0.4) > MAX_Y:
                new_content_slide()
            add_textbox(current_slide, text,
                        Inches(0.5 + b["level"] * 0.3), y_cursor,
                        prs.slide_width - Inches(1.0), Inches(0.4),
                        font_size=11)
            y_cursor += Inches(0.4)

        elif b["type"] == "table":
            # Tables always get their own slide
            new_content_slide()
            add_table_slide(current_slide, b["headers"], b["rows"])
            y_cursor = MAX_Y  # force next block to new slide

    prs.save(output_path)
    return output_path


# ─── MAIN ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Export a filled BABOK markdown template to Word, Excel, or PowerPoint."
    )
    parser.add_argument("--input", required=True, help="Path to the filled markdown file")
    parser.add_argument("--format", required=True, choices=["docx", "xlsx", "pptx"],
                        help="Output format: docx, xlsx, or pptx")
    parser.add_argument("--section", default=None,
                        help="Section letter to extract (e.g. A, B, C). Exports all if omitted.")
    parser.add_argument("--out", default="outputs",
                        help="Output directory (default: outputs/)")
    parser.add_argument("--title", default=None,
                        help="Custom document title")

    args = parser.parse_args()

    # ── Validate input
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    md_text = input_path.read_text(encoding="utf-8")

    # ── Parse
    blocks = parse_markdown(md_text)

    # ── Filter section if requested
    if args.section:
        blocks = extract_section(blocks, args.section)

    # ── Build title
    doc_title = args.title or (
        f"{input_path.stem.replace('-', ' ').title()}"
        + (f" — Section {args.section.upper()}" if args.section else "")
    )

    # ── Output path
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    section_tag = f"_sec{args.section.upper()}" if args.section else ""
    filename = f"{input_path.stem}{section_tag}_{timestamp}.{args.format}"
    output_path = out_dir / filename

    # ── Export
    exporters = {
        "docx": export_docx,
        "xlsx": export_xlsx,
        "pptx": export_pptx,
    }
    result = exporters[args.format](blocks, output_path, doc_title)

    print(f"[OK] Exported: {result.resolve()}")
    return str(result.resolve())


if __name__ == "__main__":
    main()
